# Generated by Django 5.2.1 on 2025-08-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=128)),
                ("address", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
