# Generated by Django 5.2.1 on 2025-08-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_address_alter_user_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=100)),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("Video", "Video"),
                            ("Course", "Course"),
                            ("Article", "Article"),
                        ],
                        max_length=20,
                    ),
                ),
                ("platform", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
