# Generated by Django 5.2.1 on 2025-08-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_goal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="goal",
            name="resource",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.CharField(max_length=20),
        ),
    ]
